# Generated by Django 4.1.7 on 2023-05-31 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_polls"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Polls",
            new_name="Tags",
        ),
    ]
